baseURL = "omarabid59.github.io"
languageCode = "en-us"
title = "Omar Abid"
theme = "hyde-hyde"


[params]
    author = "Omar Abid"
    title = "Portfolio"
    # description = "..."
    authorimage = "/img/headshot.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "Omar Abid"
    #license = "CC BY-SA 4.0"
    #licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    #showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"
    toc = "hugo"

[params.social]
    github = "omarabid59"
    linkedin = "omarabid4"
    email = "omar.abid4@gmail.com"


## Main Menu
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
